#!/bin/bash                                                                                                                           

cat $1 | sed \
  -e "s/.*\^.*//g" \
  -e "s/www//g" \
  -e "s/yyy//g" \
  -e "s/xxx//g" \
  -e "s/\[.*\]//g" \
  -e "s/\[\=\!//g" \
  -e 's/<.*>//g' \
  -e 's/<//g' \
  -e 's/ \.//g' \
  -e 's/ ?//g' \
  -e 's/ !//g' \
  -e 's/\///g' \
  -e 's/&imit:.*//g' \
  -e 's/&.*//g' \
  -e 's/ ,//g' \
  -e 's/,//g' \
  -e 's/(//g' \
  -e 's/)//g' \
  -e "s/\.//g" \
  -e "s/“//g" \
  -e "s/”//g" \
  -e "s/@si//g" \
  -e "s/@.//g" \
  -e "s/@..//g" \
  -e "s/&=.*//g" \
  -e "s/.*@b//g" \
  -e "s/ah:/ah/g" \
  -e "s/o:h/oh/g" \
  -e "s/://g" \
  -e "s/+//g" \
  -e "s/_/ /g" \
  -e 's/\"//g' \
  -e "s/\/\n//g" \
  -e "s/  */ /g" \
  -e '/^$/d'
